### PR TITLE
Disable back button and gesture only in room

### PR DESCRIPTION
**Pull request by maksg**
## Description

Enable back button for preview screen and disable back gesture for room screen in `fishjam-chat`.

## Motivation and Context

If I make a mistake in credentials for joining room I would like to be able to close the screen and fix it. Currently only the back gesture wasn't disabled and could be used to go back.

Additionally, I could use the gesture to go back from the room screen instead of having to tap end call button.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by MiloszFilimowski — COMMENTED** [review]
I think we'd also need to call `leaveRoom` when this screen is closed as we need to clear any created tracks.

**Comment by maksg** [comment]
I don't think that's the case as `joinRoom` is only called after tapping `Join room` button in preview screen. And going to the preview screen doesn't do much besides setting connection error to null and passing some parameters:
```
setConnectionError(null);
navigation.navigate('Preview', {
  fishjamUrl: fishjamUrl.trim(),
  participantToken: participantToken.trim(),
});
```

**Comment by MiloszFilimowski** [comment]
Unfortunately, the API is not clear here. `PreviewScreen` calls `prepareCamera` which creates a local video track. This track is not removed until `leaveRoom` is called. This was the reason for this PR: https://github.com/fishjam-cloud/mobile-client-sdk/pull/121

**Comment by maksg** [comment]
Ah, I see. In that case I added calling `leaveRoom` when the preview screen is supposed to close.

**Review by MiloszFilimowski — APPROVED** [review]

**Pull request merged**
